#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Secure Integration Example
===========================

Demonstrates integration with Flask-Login for authentication.

This example shows:
- User authentication with Flask-Login
- Role-based access control
- Secure log viewing
- Login/logout functionality

Usage:
    pip install Flask-Login
    python examples/secure_integration.py

Login credentials:
    - Admin: username=admin, password=admin123
    - User: username=user, password=user123
"""

import logging
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from flask import Flask, redirect, url_for, request, flash
from flask_login import (
    LoginManager,
    UserMixin,
    login_user,
    logout_user,
    login_required,
    current_user,
)

from immutable_log_widget import (
    ImmutableLogWidget,
    ImmutableLogWidgetConfig,
    ImmutableFileHandler,
)
from immutable_log_widget.utils.security import flask_login_required


app = Flask(__name__)
app.secret_key = "super-secret-key-change-in-production"

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = "login"

LOG_FILE = os.path.join(os.path.dirname(__file__), "secure_app.log")

logger = logging.getLogger("secure_app")
logger.setLevel(logging.INFO)
handler = ImmutableFileHandler(LOG_FILE)
formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")
handler.setFormatter(formatter)
logger.addHandler(handler)


class User(UserMixin):
    def __init__(self, id, username, password, roles=None):
        self.id = id
        self.username = username
        self.password = password
        self.roles = roles or []

    def has_role(self, role):
        return role in self.roles


users = {
    "admin": User("1", "admin", "admin123", ["admin", "user"]),
    "user": User("2", "user", "user123", ["user"]),
}


@login_manager.user_loader
def load_user(user_id):
    for user in users.values():
        if user.id == user_id:
            return user
    return None


config = ImmutableLogWidgetConfig(
    log_file_path=LOG_FILE, auth_decorator=flask_login_required, enable_download=True
)

widget = ImmutableLogWidget(app, config)


@app.route("/")
def index():
    if current_user.is_authenticated:
        status = f"Logged in as: {current_user.username}"
        actions = f"""
            <li><a href="/generate-logs">Generate Logs</a></li>
            <li><a href="{widget.get_viewer_url()}">View Logs (Protected)</a></li>
            <li><a href="/logout">Logout</a></li>
        """
    else:
        status = "Not logged in"
        actions = '<li><a href="/login">Login</a></li>'

    return f"""
    <h1>Secure Integration Example</h1>
    <p><strong>Status:</strong> {status}</p>
    <h2>Actions:</h2>
    <ul>{actions}</ul>
    <hr>
    <h3>Test Credentials:</h3>
    <ul>
        <li>Admin: username=admin, password=admin123</li>
        <li>User: username=user, password=user123</li>
    </ul>
    """


@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        user = users.get(username)
        if user and user.password == password:
            login_user(user)
            logger.info(f"User logged in: {username}")
            flash(f"Welcome, {username}!", "success")
            return redirect(url_for("index"))
        else:
            logger.warning(f"Failed login attempt: {username}")
            flash("Invalid credentials", "error")

    return """
    <h1>Login</h1>
    <form method="post">
        <p>
            <label>Username:</label><br>
            <input type="text" name="username" required>
        </p>
        <p>
            <label>Password:</label><br>
            <input type="password" name="password" required>
        </p>
        <p><button type="submit">Login</button></p>
    </form>
    <p><a href="/">Back to Home</a></p>
    """


@app.route("/logout")
@login_required
def logout():
    username = current_user.username
    logout_user()
    logger.info(f"User logged out: {username}")
    flash("Logged out successfully", "info")
    return redirect(url_for("index"))


@app.route("/generate-logs")
@login_required
def generate_logs():
    """Generate sample logs (requires authentication)."""
    logger.info(f"Logs generated by user: {current_user.username}")
    logger.debug("Debug message")
    logger.info("Info message")
    logger.warning("Warning message")
    logger.error("Error message")

    return f"""
    <h2>Logs Generated!</h2>
    <p>Sample logs have been created.</p>
    <p><a href="/">Home</a> | <a href="{widget.get_viewer_url()}">View Logs</a></p>
    """


if __name__ == "__main__":
    logger.info("=" * 50)
    logger.info("Secure application starting")
    logger.info(f"Log file: {LOG_FILE}")
    logger.info("=" * 50)

    print("\n" + "=" * 60)
    print("Immutable Log Widget - Secure Example")
    print("=" * 60)
    print("Login credentials:")
    print("  Admin: username=admin, password=admin123")
    print("  User:  username=user, password=user123")
    print("=" * 60)
    print("URL: http://localhost:5000")
    print("=" * 60 + "\n")

    app.run(debug=True, port=5000)
